[package]
name = "AlfredTodWorkflow"
version = "0.2.6"
license = "MIT"
repository = "https://github.com/stacksjb/AlfredTodWorkflow/"

[dependencies]
dependency-crate = { git = "https://github.com/alanvardy/tod", branch = "main" }
